### ISSUE TITLE
Strange vimeo thumbnail url issue

### ISSUE THREAD

**Issue by drakmail** [thibaudgg/video_info#170]
When I'm trying to get vimeo thumbnail (through scraper) I always getting this image:

![image example](https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F607241994_640.jpg)

Steps to reproduce:

```ruby
video = VideoInfo.new('https://vimeo.com/193970014')
video.thumbnail_medium
# => "https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F607241994_200x150.jpg"
```

One more thing: if I remove vimeocdn filter part of string (for example, if I left only this part: `https://i.vimeocdn.com/video/607241847_200x150.jpg`) than I getting valid image:

![valid image example](https://i.vimeocdn.com/video/607241847_200x150.jpg)

**Comment by vheuken** [comment]
We're getting the image URLs from some JSON we ripped from a script tag (hacky, I know) and just modifying the resolution on the URL. It looks like the proper way would be to get them from meta tags, [which we already have code to do.](https://github.com/vheuken/video_info/blob/master/lib/video_info/providers/vimeo_scraper.rb#L150). The URL [here](https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F607241994_1280x1280.webp&src1=https%3A%2F%2Ff.vimeocdn.com%2Fimages_v6%2Fshare%2Fplay_icon_overlay.png) works fine, despite being the same format as what we're returning now:

```html
    <meta property="og:image" content="https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F607241994_1280x1280.webp&src1=https%3A%2F%2Ff.vimeocdn.com%2Fimages_v6%2Fshare%2Fplay_icon_overlay.png">
```

The `https://i.vimeocdn.com/filter/overlay?` stuff appears to add a play icon overlay. [Changing the resolution via the image URL also seems to work fine.](https://i.vimeocdn.com/filter/overlay?src0=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F607241994_250x150.webp&src1=https%3A%2F%2Ff.vimeocdn.com%2Fimages_v6%2Fshare%2Fplay_icon_overlay.png).

We could parse out the image URL so that we don't have the overlay, but I'd imagine that'd make things much more prone to breakage. With the scraper I think it's better that things _work_ rather than work _optimally_ (people can get an API key if they need that), so for now I'm just going to make it return the meta tag URL as is (modifying the resolution of course). If you think it's worth removing the overlay, let me know.

**Comment by vheuken** [comment]
Looking at the videos in our tests, it looks like your video is actually a special case. Other videos don't have the overlay. [This video](https://vimeo.com/136971428) just has this: `<meta property="og:image" content="https://i.vimeocdn.com/video/531688239_1280x720.webp">`

I'm thinking we won't need different code to handle it (just gonna throw some regex at it...), but I'll add it to the unit tests.

**Comment by vheuken** [comment]
It's fixed in master. I'll push a new gem out tonight. [It ended up being simpler to just remove the overlay. ](https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/vimeo_scraper.rb#L147)

**Comment by vheuken** [comment]
@drakmail  2.7 has been released on Ruby Gems. Feel free to upgrade.

**Comment by fdc263** [comment]
looks like it happened again
video: https://vimeo.com/612038106
thumbnail_large: https://i.vimeocdn.com/video/1249489398_640.jpg
