### ISSUE TITLE
Doesn't work well with frozen strings

### ISSUE THREAD

**Issue by Mrjaco12** [thibaudgg/video_info#172]
ruby version - `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
VideoInfo version - `2.7`

Reproduce:

```Ruby
url = "//player.vimeo.com/video/22439234".freeze
VideoInfo.new(url)
```

Error: 

`RuntimeError: can't modify frozen String`
`from /usr/local/lib/ruby/gems/2.4.0/gems/video_info-2.7/lib/video_info/providers/vkontakte.rb:16:in 'strip!'`

Looks like there are two places in the `vkontakte.rb` file where `strip!` is used. It should be fairly easy to move those over to `.strip`. I can work up a PR sometime later this week if that would be welcome.

**Comment by vheuken** [comment]
Thanks for the report. I'll hopefully get to it soon. If I don't, feel free
to submit a PR!

I actually never thought about this case. I will keep it in mind moving
forward.

On Mar 6, 2017 8:33 AM, "Jacob" <notifications@github.com> wrote:

ruby version - ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
VideoInfo version - 2.7

Reproduce:

url = "//player.vimeo.com/video/22439234".freezeVideoInfo.new(url)

Error:

RuntimeError: can't modify frozen String
from /usr/local/lib/ruby/gems/2.4.0/gems/video_info-2.7/lib/
video_info/providers/vkontakte.rb:16:instrip!'`

Looks like there are two places in the vkontakte.rb file where strip! is
used. It should be fairly easy to move those over to .strip. I can work up
a PR sometime later this week if that would be welcome.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thibaudgg/video_info/issues/172>, or mute the thread

**Comment by vheuken** [comment]
@Mrjaco12 Fix should be in master now! It'll be pushed out in a new version soon enough. For now, you can use this in your Gemfile:

`gem 'video_info', git: 'https://github.com/thibaudgg/video_info.git'`

**Comment by Mrjaco12** [comment]
Dude, great work! Thanks a ton. It's always great to use an active well maintained project.
