### ISSUE TITLE
VideoInfo doesn't convert networking errors into custom exceptions

### ISSUE THREAD

**Issue by paneq** [thibaudgg/video_info#62]
Which means client of the library must look into its implementation details to know what to catch.

**Comment by thibaudgg** [comment]
Ok not good, could you please submit a PR to fix that? Thanks! :heart_decoration:

**Comment by thibaudgg** [comment]
@paneq are you still interested to fix that?

**Comment by paneq** [comment]
@thibaudgg are you ok with dependency on `net_http_timeout_errors` gem for that?

**Comment by thibaudgg** [comment]
Sure, the gem looks fine.

**Comment by thibaudgg** [comment]
@vheuken maybe it would solve/explain our problem on travis-ci, what do you think?

**Comment by vheuken** [comment]
Actually, I think the Travis issue was just temporary. I was pushing some stuff earlier today and Travis seemed fine: https://travis-ci.org/vheuken/video_info/builds/65020229 (failing because work is in progress, but not stalling/timing out). Except JRuby. Jruby seems to have issues with some Vkontakte stuff.

That being said, if @paneq lost interest in implementing this, I could certainly give it a shot. What exactly would that entail, though? Would I just make a function that takes the HTTP response code and have it throw a `NetworkError` with a message that contains the exact error code? Or a custom exception for every feasible error code (`403NetworkError`, etc)?

**Comment by thibaudgg** [comment]
@paneq what did you had in mind?

**Comment by paneq** [comment]
I had in mind:

```ruby
class VideoInfo
  class Error < StandardError; end
  class UrlError < Error; end
  class HttpError < Error; end
end

class Provider
  def method
    http_thing
  rescue *NetHttpTimeoutErrors.all
    raise VideoInfo::CommunicationError
  end
end
```

The best place to wrap this logic seems to be `_set_data_from_api` I think after looking quickly in the code.

**Comment by vheuken** [comment]
@paneq Thanks. I'll handle this after I finish #79

**Comment by thibaudgg** [comment]
:+1:

**Comment by paneq** [comment]
Just got one more error `OpenURI::HTTPError` on production which is not covered by `NetHttpTimeoutErrors.all` :)

**Comment by thibaudgg** [comment]
@vheuken still interested to fix that one? (it would be great!)

**Comment by vheuken** [comment]
Yeah, I'll try implementing this sometime this week. Should be relatively simple.

**Comment by thibaudgg** [comment]
:+1:
